services:
  - type: web
    name: monopoly-socket-server
    env: node
    rootDir: apps/server
    plan: free
    buildCommand: |
      corepack enable
      pnpm install --frozen-lockfile
      pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: WEB_ORIGIN
        value: https://monopoly-with-friends.vercel.app/
    autoDeploy: true
